version: '2'
services:
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - micro
  web:
    depends_on:
      - redis
    build: ./web
    ports:
      - 8300:8300
    networks:
      - micro
  service1:
    depends_on:
      - redis
    build: ./service1
    ports:
      - 8301:8301
    networks:
      - micro
  service2:
    depends_on:
      - redis
    build: ./service2
    ports:
      - 8302:8302
    networks:
      - micro
networks:
  micro: